# Generated by Django 2.1.5 on 2019-01-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrlica_ime', models.CharField(max_length=10)),
                ('ogrlica_opis', models.TextField(max_length=100)),
                ('pristen_ime', models.CharField(max_length=10)),
                ('prsten_opis', models.TextField(max_length=100)),
            ],
        ),
    ]
