# Generated by Django 2.1.5 on 2019-01-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Novi_app', '0003_festival_stand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=40)),
                ('num_song', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('artist_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt', models.PositiveSmallIntegerField(choices=[(1, 'Rock'), (2, 'Metal'), (3, 'Rap'), (4, 'Country')])),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novi_app.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novi_app.Music'),
        ),
    ]
